# Generated by Django 3.2.5 on 2021-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lesson_lessondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondetail',
            name='banner_img',
            field=models.ImageField(null=True, upload_to='lessons'),
        ),
        migrations.AlterField(
            model_name='lessondetail',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
