# Generated by Django 3.2.5 on 2021-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210903_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondetail',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='lessons'),
        ),
    ]
