# Generated by Django 3.2.5 on 2021-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lessondetail_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='lessons'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='days',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LessonDetail',
        ),
    ]
