# Generated by Django 3.2.5 on 2021-09-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_classroom_classroomnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='time',
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_details',
            field=models.URLField(blank=True, null=True),
        ),
    ]
