# Generated by Django 3.2.5 on 2021-09-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210907_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
