# Generated by Django 3.2.5 on 2021-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='tutor_void',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='state',
            field=models.CharField(choices=[('CR', 'Created'), ('AC', 'Awaiting Confirmation'), ('CF', 'Confirmed'), ('UP', 'Upcoming'), ('CP', 'Complete'), ('PR', 'Part Reviewed'), ('FR', 'Fully Reviewed'), ('CL', 'Closed')], default='CR', max_length=2),
        ),
    ]
