# Generated by Django 3.2.5 on 2021-09-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210906_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dollours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
