# Generated by Django 3.2.5 on 2021-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_dollours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classroom_complete',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
