# Generated by Django 3.2.5 on 2021-09-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_classroom_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
