# Generated by Django 3.2.5 on 2021-09-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
